const Categories = [
  {
    id: 1,
    image: require('../assets/images/healing1.png'),
    category: '4 main Elements',
    description: 'Wiz Khalifa',
    url:
      'https://cdn.beatzjam.com/wp-content/uploads/2021/Wiz-Khalifa-ft-Charlie-Puth-See-You-Again-(BeatzJam.com).mp3',
    fav: false,
  },
  {
    id: 2,
    image: require('../assets/images/healing2.png'),
    category: 'Brain clearing',
    description: 'Billie Eilish, Khalid',
    url: 'https://pagaliworld.com/files/download/id/3260',
    fav: false,
  },
  {
    id: 3,
    image: require('../assets/images/healing3.png'),
    category: 'Stress and Anxiety',
    description: 'Ed Sheeran',
    url:
      'https://cdn.beatzjam.com/wp-content/uploads/2021/Ed-Sheeran-Shape-Of-You-(BeatzJam.com).mp3',
    fav: false,
  },
  {
    id: 4,
    image: require('../assets/images/healing4.png'),
    category: 'Detox and Immune Function',
    description: 'Jeni Loz',
    url: 'https://paglasongs.com/files/download/id/2162',
    fav: false,
  },
  {
    id: 5,
    image: require('../assets/images/healing5.png'),
    category: 'Endocrine system -Hormone balancing',
    description: 'Justin Bieber',
    url: 'https://pagalworld.com.se/files/download/id/1505',
    fav: false,
  },
  {
    id: 6,
    image: require('../assets/images/healing6.png'),
    category: 'Heart & Lung Function',
    description: 'Alec Benjamin',
    url:
      'https://songszilla.net/files/download/id/2153&volume=75&showstop=1&showvolume=1',
    fav: false,
  },
  {
    id: 7,
    image: require('../assets/images/healing7.png'),
    category: 'Liver & Kidneys & Arteries',
    description: '	Jeni Loz',
    url: 'https://paglasongs.com/files/download/id/2162',
    fav: false,
  },
  {
    id: 8,
    image: require('../assets/images/healing8.png'),
    category: 'Balance of ph. in the body',
    description: 'Justin Bieber',
    url: 'https://pagalworld.com.se/files/download/id/1505',
    fav: false,
  },
  {
    id: 9,
    image: require('../assets/images/healing9.png'),
    category: 'Digestive, Respiratory & Circulatory systems',
    description: 'Alec Benjamin',
    url:
      'https://songszilla.net/files/download/id/2153&volume=75&showstop=1&showvolume=1',
    fav: false,
  },
  {
    id: 10,
    image: require('../assets/images/healing5.png'),
    category: 'Healing for general wellbeing and pain',
    description: 'Justin Bieber',
    url: 'https://pagalworld.com.se/files/download/id/1505',
    fav: false,
  },
  {
    id: 11,
    image: require('../assets/images/healing2.png'),
    category: 'Grounding, Chakra balancing, Meridian energy',
    description: 'Billie Eilish, Khalid',
    url: 'https://pagaliworld.com/files/download/id/3260',
    fav: false,
  },
  {
    id: 12,
    image: require('../assets/images/healing12.jpg'),
    category: '30 Minute Healing',
    description: 'Billie Eilish, Khalid',
    url: 'https://pagaliworld.com/files/download/id/3260',
    fav: false,
  },
];
export default Categories;
