export default Songs = [
  {
    id: 1,
    url:
      'https://cdn.beatzjam.com/wp-content/uploads/2021/Wiz-Khalifa-ft-Charlie-Puth-See-You-Again-(BeatzJam.com).mp3',
    title: 'See you Again',
    artist: 'Wiz Khalifa',
    artwork: require('../assets/images/healing1.png'),
    rating: false,
    duration: 232,
  },
  {
    id: 2,
    url: 'https://pagaliworld.com/files/download/id/3260',
    title: 'Lovely',
    artist: 'Billie Eilish, Khalid',
    artwork: require('../assets/images/healing2.png'),
    rating: false,
    duration: 200,
  },
  {
    id: 3,
    url:
      'https://cdn.beatzjam.com/wp-content/uploads/2021/Ed-Sheeran-Shape-Of-You-(BeatzJam.com).mp3',

    artwork: require('../assets/images/healing3.png'),
    title: 'Shape of you',
    artist: 'Ed Sheeran',
    rating: false,
    duration: 239,
  },
  {
    id: 4,
    artwork: require('../assets/images/healing4.png'),
    title: 'Play Date',
    artist: 'Jeni Loz',
    url: 'https://paglasongs.com/files/download/id/2162',
    rating: false,
    duration: 180,
  },
  {
    id: 5,
    artwork: require('../assets/images/healing5.png'),
    title: 'Peaches',
    artist: 'Justin Bieber',
    url: 'https://pagalworld.com.se/files/download/id/1505',
    rating: false,
    duration: 197,
  },
  {
    id: 6,
    artwork: require('../assets/images/healing6.png'),
    title: 'Let Me Down Slowly',
    artist: 'Alec Benjamin',
    url:
      'https://songszilla.net/files/download/id/2153&volume=75&showstop=1&showvolume=1',
    rating: false,
    duration: 169,
  },
  {
    id: 7,
    artwork: require('../assets/images/healing7.png'),
    title: 'Play Date',
    artist: 'Jeni Loz',
    url: 'https://paglasongs.com/files/download/id/2162',
    rating: false,
    duration: 180,
  },
  {
    id: 8,
    artwork: require('../assets/images/healing8.png'),
    title: 'Peaches',
    artist: 'Justin Bieber',
    url: 'https://pagalworld.com.se/files/download/id/1505',
    rating: false,
    duration: 197,
  },
  {
    id: 9,
    artwork: require('../assets/images/healing9.png'),
    title: 'Let Me Down Slowly',
    artist: 'Alec Benjamin',
    url:
      'https://songszilla.net/files/download/id/2153&volume=75&showstop=1&showvolume=1',
    rating: false,
    duration: 169,
  },
];
